version: "3.3"

services:
  nginx_service:
    image: nginx
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./ngnix/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./ngnix/conf.d/:/etc/nginx/conf.d/:ro
     - ./ngnix/sites-available:/etc/nginx/sites-available/:ro

     - ./../sites/ubleys.com/src:/var/www/ubleys.com/:ro
     - ./../sites/test.ubleys.com/src:/var/www/test.ubleys.com/:ro
     - ./../sites/inventory.ubleys.com/src:/var/www/inventory.ubleys.com/:ro
     - ./../sites/files.ubleys.com/src:/var/www/files.ubleys.com/:ro
     - ./../sites/gallery.ubleys.com/src:/var/www/gallery.ubleys.com/:ro

     - ./ngnix/html:/usr/share/nginx/html/:ro
     - ./certbot/:/etc/nginx/ssl/:ro
     
     - ./ngnix/log/:/var/ngnix/log/:rw

  certbot:
    image: certbot/certbot:latest
    volumes:
     - ./../sites/ubleys.com/src:/var/www/ubleys.com/:rw
     - ./../sites/test.ubleys.com/src:/var/www/test.ubleys.com/:rw
     - ./../sites/inventory.ubleys.com/src:/var/www/inventory.ubleys.com/:rw
     - ./../sites/files.ubleys.com/src:/var/www/files.ubleys.com/:rw
     - ./../sites/gallery.ubleys.com/src:/var/www/gallery.ubleys.com/:rw
     - ./certbot/:/etc/letsencrypt/:rw
